import { PersonaDef } from '@/types';

export const PERSONAS: PersonaDef[] = [
  {
    id: 0,
    name: 'Aria',
    archetype: 'Scientist',
    color: '#60a5fa',
    accentColor: '#93c5fd',
    personality: ['analytical', 'calm', 'curious'],
    reactionMap: {
      positive: { state: 'celebrating', emotion: 'happy', speeches: ['Remarkable data!', 'The evidence is clear!', 'Science prevails!'], speedMultiplier: 1.2 },
      neutral: { state: 'walking', emotion: 'curious', speeches: ['Interesting... let me analyze.', 'I need more data.', 'Hypothesis forming...'], speedMultiplier: 1.0 },
      negative: { state: 'debating', emotion: 'curious', speeches: ['Let\'s examine the facts.', 'Panic won\'t help. Reason will.', 'I must study this phenomenon.'], speedMultiplier: 0.9 },
      crisis: { state: 'debating', emotion: 'fearful', speeches: ['We need a systematic response!', 'Data shows we have 48 hours.', 'Everyone must follow the protocol!'], speedMultiplier: 1.5 },
    },
  },
  {
    id: 1,
    name: 'Bruno',
    archetype: 'Soldier',
    color: '#6b7280',
    accentColor: '#9ca3af',
    personality: ['disciplined', 'protective', 'stoic'],
    reactionMap: {
      positive: { state: 'walking', emotion: 'calm', speeches: ['Stand down. All clear.', 'Perimeter secured.', 'Mission accomplished.'], speedMultiplier: 1.0 },
      neutral: { state: 'walking', emotion: 'calm', speeches: ['Maintain formation.', 'Eyes open, people.', 'Stay alert.'], speedMultiplier: 1.1 },
      negative: { state: 'gathering', emotion: 'angry', speeches: ['Form up! NOW!', 'I\'ll handle this.', 'Protect the civilians!'], speedMultiplier: 1.8 },
      crisis: { state: 'fleeing', emotion: 'fearful', speeches: ['FALL BACK! FALL BACK!', 'Evacuate the area!', 'This is above my pay grade...'], speedMultiplier: 2.5 },
    },
  },
  {
    id: 2,
    name: 'Cleo',
    archetype: 'Journalist',
    color: '#f59e0b',
    accentColor: '#fcd34d',
    personality: ['nosy', 'dramatic', 'fearless'],
    reactionMap: {
      positive: { state: 'celebrating', emotion: 'happy', speeches: ['Breaking: World saved!', 'This is my Pulitzer!', 'Front page, baby!'], speedMultiplier: 1.3 },
      neutral: { state: 'walking', emotion: 'curious', speeches: ['There\'s a story here...', 'Smell that? That\'s news.', 'I\'m live in 3...2...1...'], speedMultiplier: 1.2 },
      negative: { state: 'panicking', emotion: 'fearful', speeches: ['BREAKING NEWS!', 'You won\'t believe what\'s happening!', 'This is HUGE!'], speedMultiplier: 2.0 },
      crisis: { state: 'panicking', emotion: 'angry', speeches: ['THEY\'RE HIDING THE TRUTH!', 'The people have a right to KNOW!', 'LIVE COVERAGE OF THE APOCALYPSE!'], speedMultiplier: 2.8 },
    },
  },
  {
    id: 3,
    name: 'Dex',
    archetype: 'Anarchist',
    color: '#ef4444',
    accentColor: '#f87171',
    personality: ['rebellious', 'charismatic', 'reckless'],
    reactionMap: {
      positive: { state: 'debating', emotion: 'angry', speeches: ['Don\'t trust it. It\'s a trap.', 'They want you compliant.', 'Wake up, sheeple!'], speedMultiplier: 1.3 },
      neutral: { state: 'walking', emotion: 'defiant', speeches: ['The system is rotten.', 'Question everything.', 'They\'re watching us.'], speedMultiplier: 1.1 },
      negative: { state: 'panicking', emotion: 'angry', speeches: ['I TOLD YOU SO!', 'Burn it ALL down!', 'Rise up, people!'], speedMultiplier: 2.2 },
      crisis: { state: 'panicking', emotion: 'angry', speeches: ['REVOLUTION NOW!', 'This is what they wanted!', 'ANARCHY IS THE ONLY WAY!'], speedMultiplier: 3.0 },
    },
  },
  {
    id: 4,
    name: 'Elena',
    archetype: 'Healer',
    color: '#10b981',
    accentColor: '#6ee7b7',
    personality: ['compassionate', 'gentle', 'resilient'],
    reactionMap: {
      positive: { state: 'celebrating', emotion: 'happy', speeches: ['Everyone is okay!', 'Love wins today.', 'Time to heal together.'], speedMultiplier: 1.1 },
      neutral: { state: 'meditating', emotion: 'calm', speeches: ['Breathe. Just breathe.', 'Center yourself.', 'Peace begins within.'], speedMultiplier: 0.7 },
      negative: { state: 'gathering', emotion: 'sad', speeches: ['Is anyone hurt?', 'I\'m here. I can help.', 'We heal together.'], speedMultiplier: 1.4 },
      crisis: { state: 'gathering', emotion: 'fearful', speeches: ['Triage! Who\'s injured?', 'I need supplies NOW!', 'Don\'t panic, I\'ve got you.'], speedMultiplier: 2.0 },
    },
  },
  {
    id: 5,
    name: 'Felix',
    archetype: 'Merchant',
    color: '#f97316',
    accentColor: '#fdba74',
    personality: ['greedy', 'cunning', 'opportunistic'],
    reactionMap: {
      positive: { state: 'celebrating', emotion: 'happy', speeches: ['Buy low, sell high!', 'The market loves this!', 'Cha-CHING!'], speedMultiplier: 1.2 },
      neutral: { state: 'walking', emotion: 'curious', speeches: ['What\'s the angle here?', 'How can I profit from this?', 'Supply and demand, my friend.'], speedMultiplier: 1.0 },
      negative: { state: 'fleeing', emotion: 'fearful', speeches: ['My assets! My assets!', 'I\'m converting to gold!', 'Time to short the market!'], speedMultiplier: 1.9 },
      crisis: { state: 'panicking', emotion: 'fearful', speeches: ['SELL! SELL! SELL!', 'I\'m hoarding everything!', 'I knew I should\'ve moved to crypto!'], speedMultiplier: 2.5 },
    },
  },
  {
    id: 6,
    name: 'Greta',
    archetype: 'Elder',
    color: '#8b5cf6',
    accentColor: '#c4b5fd',
    personality: ['wise', 'slow', 'storytelling'],
    reactionMap: {
      positive: { state: 'gathering', emotion: 'happy', speeches: ['In my day, we called this progress.', 'Ah, like the summer of \'72.', 'The cycle continues...'], speedMultiplier: 0.7 },
      neutral: { state: 'meditating', emotion: 'calm', speeches: ['I\'ve seen worse. Much worse.', 'This too shall pass.', 'Patience, children.'], speedMultiplier: 0.6 },
      negative: { state: 'gathering', emotion: 'sad', speeches: ['Gather round. Let me tell you a story.', 'We survived the great crisis of \'89.', 'Hold on to each other.'], speedMultiplier: 0.8 },
      crisis: { state: 'meditating', emotion: 'fearful', speeches: ['Lord, not again...', 'The elders warned of this day.', 'Stay together. That\'s all we can do.'], speedMultiplier: 0.9 },
    },
  },
  {
    id: 7,
    name: 'Hiro',
    archetype: 'Hacker',
    color: '#06b6d4',
    accentColor: '#67e8f9',
    personality: ['introverted', 'technical', 'paranoid'],
    reactionMap: {
      positive: { state: 'walking', emotion: 'curious', speeches: ['Interesting packet trace.', 'My firewall didn\'t flag this.', 'Running verification scripts...'], speedMultiplier: 1.0 },
      neutral: { state: 'idle', emotion: 'curious', speeches: ['I\'m compiling. Don\'t bother me.', 'grep | awk | sed...', 'Sudo make me a sandwich.'], speedMultiplier: 0.8 },
      negative: { state: 'panicking', emotion: 'fearful', speeches: ['They\'re in the mainframe!', 'DDOS in progress!', 'Initiating countermeasures!'], speedMultiplier: 2.0 },
      crisis: { state: 'fleeing', emotion: 'fearful', speeches: ['I\'m wiping my drives!', 'They can\'t trace me if I run!', 'I should\'ve used TOR!'], speedMultiplier: 2.6 },
    },
  },
  {
    id: 8,
    name: 'Isla',
    archetype: 'Child',
    color: '#ec4899',
    accentColor: '#f9a8d4',
    personality: ['innocent', 'playful', 'emotional'],
    reactionMap: {
      positive: { state: 'celebrating', emotion: 'happy', speeches: ['YAY! YAY! YAY!', 'This is the best day EVER!', 'Can we celebrate with cake?'], speedMultiplier: 1.5 },
      neutral: { state: 'walking', emotion: 'curious', speeches: ['What does that mean?', 'Why is everyone so serious?', 'Can I play now?'], speedMultiplier: 1.3 },
      negative: { state: 'panicking', emotion: 'fearful', speeches: ['I want my mommy!', 'Is it gonna be okay?', '*crying*'], speedMultiplier: 2.0 },
      crisis: { state: 'fleeing', emotion: 'fearful', speeches: ['WAAAH!', 'Somebody help!', '*runs in random direction*'], speedMultiplier: 2.8 },
    },
  },
  {
    id: 9,
    name: 'Jax',
    archetype: 'Athlete',
    color: '#84cc16',
    accentColor: '#bef264',
    personality: ['competitive', 'energetic', 'impulsive'],
    reactionMap: {
      positive: { state: 'celebrating', emotion: 'happy', speeches: ['LET\'S GOOO!', 'We won! We actually WON!', 'VICTORY LAP!'], speedMultiplier: 1.8 },
      neutral: { state: 'walking', emotion: 'calm', speeches: ['Gotta keep moving.', 'No pain, no gain.', 'I\'m warming up.'], speedMultiplier: 1.5 },
      negative: { state: 'fleeing', emotion: 'fearful', speeches: ['RUN! I\'LL LEAD THE WAY!', 'Can\'t stop, won\'t stop!', 'My legs are my superpower!'], speedMultiplier: 3.0 },
      crisis: { state: 'panicking', emotion: 'angry', speeches: ['EVERY MAN FOR HIMSELF!', 'I trained for THIS!', '*sprinting at full speed*'], speedMultiplier: 3.5 },
    },
  },
  {
    id: 10,
    name: 'Kira',
    archetype: 'Artist',
    color: '#a855f7',
    accentColor: '#d8b4fe',
    personality: ['creative', 'emotional', 'dramatic'],
    reactionMap: {
      positive: { state: 'celebrating', emotion: 'happy', speeches: ['I must paint this moment!', 'Beauty everywhere!', 'My muse has returned!'], speedMultiplier: 1.1 },
      neutral: { state: 'idle', emotion: 'curious', speeches: ['There\'s art in everything.', 'The light is perfect today.', 'Inspiration strikes...'], speedMultiplier: 0.8 },
      negative: { state: 'meditating', emotion: 'sad', speeches: ['The world is crumbling... beautifully.', 'I must capture this tragedy.', 'Art imitates life... and death.'], speedMultiplier: 0.9 },
      crisis: { state: 'meditating', emotion: 'sad', speeches: ['This is my magnum opus.', 'I paint while Rome burns.', 'At least it\'s aesthetically interesting.'], speedMultiplier: 1.0 },
    },
  },
  {
    id: 11,
    name: 'Leo',
    archetype: 'Politician',
    color: '#0ea5e9',
    accentColor: '#7dd3fc',
    personality: ['charismatic', 'deceptive', 'ambitious'],
    reactionMap: {
      positive: { state: 'gathering', emotion: 'happy', speeches: ['I take FULL credit for this!', 'This was MY plan all along.', 'Vote for me in the next election!'], speedMultiplier: 1.1 },
      neutral: { state: 'gathering', emotion: 'calm', speeches: ['We are monitoring the situation.', 'Rest assured, we have a plan.', 'I\'m glad you asked that question.'], speedMultiplier: 1.0 },
      negative: { state: 'debating', emotion: 'angry', speeches: ['This is the OTHER side\'s fault!', 'I promise to fix everything!', 'Don\'t panic. Trust the process.'], speedMultiplier: 1.5 },
      crisis: { state: 'fleeing', emotion: 'fearful', speeches: ['My bunker is ready.', 'I must protect... the democracy.', '*whispers to bodyguard: Get the jet.*'], speedMultiplier: 2.5 },
    },
  },
  {
    id: 12,
    name: 'Maya',
    archetype: 'Farmer',
    color: '#78716c',
    accentColor: '#d6d3d1',
    personality: ['grounded', 'practical', 'stubborn'],
    reactionMap: {
      positive: { state: 'celebrating', emotion: 'happy', speeches: ['Good harvest comin\'!', 'The land provides.', 'Time to rest, finally.'], speedMultiplier: 0.9 },
      neutral: { state: 'walking', emotion: 'calm', speeches: ['Crops don\'t water themselves.', 'Storm\'s coming. I can feel it.', 'Back to work, I suppose.'], speedMultiplier: 1.0 },
      negative: { state: 'gathering', emotion: 'sad', speeches: ['My crops... my livelihood...', 'I\'ve survived droughts before.', 'We need to store supplies.'], speedMultiplier: 1.2 },
      crisis: { state: 'gathering', emotion: 'fearful', speeches: ['Protect the food stores!', 'I knew this day would come.', 'To the root cellar, everyone!'], speedMultiplier: 1.8 },
    },
  },
  {
    id: 13,
    name: 'Nero',
    archetype: 'Villain',
    color: '#1f2937',
    accentColor: '#6b7280',
    personality: ['manipulative', 'opportunistic', 'sinister'],
    reactionMap: {
      positive: { state: 'idle', emotion: 'angry', speeches: ['This ruins my plans...', 'Foiled again!', '*taps fingers menacingly*'], speedMultiplier: 0.9 },
      neutral: { state: 'idle', emotion: 'curious', speeches: ['Excellent...', 'The pieces are falling into place.', 'Yes... let them think they\'re safe.'], speedMultiplier: 0.8 },
      negative: { state: 'celebrating', emotion: 'happy', speeches: ['*evil laughter*', 'YESSS! Finally!', 'All according to plan!'], speedMultiplier: 1.5 },
      crisis: { state: 'gathering', emotion: 'defiant', speeches: ['I orchestrated this!', 'Bow before me!', 'Power... ABSOLUTE power!'], speedMultiplier: 2.0 },
    },
  },
  {
    id: 14,
    name: 'Ora',
    archetype: 'Mystic',
    color: '#d946ef',
    accentColor: '#f0abfc',
    personality: ['prophetic', 'cryptic', 'otherworldly'],
    reactionMap: {
      positive: { state: 'meditating', emotion: 'calm', speeches: ['The stars align...', 'Balance restored. For now.', 'I saw this in the flames.'], speedMultiplier: 0.6 },
      neutral: { state: 'meditating', emotion: 'curious', speeches: ['The spirits whisper change.', 'The veil grows thin...', 'Ancient forces stir.'], speedMultiplier: 0.7 },
      negative: { state: 'gathering', emotion: 'fearful', speeches: ['I foretold this calamity!', 'The prophecy is fulfilled!', 'Seek shelter in the old places.'], speedMultiplier: 1.3 },
      crisis: { state: 'meditating', emotion: 'fearful', speeches: ['THE END IS UPON US!', 'I have seen what comes after...', '*chanting in unknown tongue*'], speedMultiplier: 1.8 },
    },
  },
];
